### ISSUE TITLE
Is the configured `Config.CacheParameter` actually being used?

### ISSUE THREAD

**Issue by joshlemer** [uberswe/golang-base-project#9]
I was looking through the project again and I see that a `CacheParameter` was added to the config which is generated at startup time in this PR https://github.com/uberswe/golang-base-project/pull/5

And each static resource is being linked to in HTML with the `c={{ .CacheParameter }}` query param e.g.  `"/assets/css/main.css?c={{ .CacheParameter }}"`, but it's not clear where or if this query parameter is actually being used. 

It seems the `cache` middleware doesn't use it, it only sets the max-age of all assets to 60 seconds but it doesn't look at the cache parameter.

**Comment by uberswe** [comment]
Hey @joshlemer thank you for bringing this up. 

The cache parameter was added to force the browser to reload css and js assets when a new version is deployed. An easy way of doing this was to automatically generate a cache parameter any time the application starts which is the default behaviour if  the `CACHE_PARAMETER` env variable is not set to anything. I also realised that some may want to handle this parameter on their own, that's why you can set it yourself if you want this to be a version number or commit hash for example.

I implemented this based on answers to the stack overflow question: [How to force the browser to reload cached CSS and JavaScript files](https://stackoverflow.com/questions/118884/how-to-force-the-browser-to-reload-cached-css-and-javascript-files)

More specifically the answer about [how someone handles invalidating css and js files in a Laravel application](https://stackoverflow.com/a/42576123/1260548).

The implementation here was done quickly, I will admit, and the 60 second timeout is directly copied from the reddit comment linked in #1 without really thinking about it. 

Now that I look at the implementation I still think it achieves the initial goal of the ticket but it's weird that the cache timeout is only 60 seconds which is perhaps ok for local development. 

I think a good solution is to make the cache expiry time configurable using an env variable, the default expiry can be changed or left at 60 seconds. What do you think about this solution @joshlemer and have I answered your question?

**Comment by uberswe** [comment]
I am going to close this now as this problem was fixed in #12 and I plan to better document the behaviour in #10
